- www/src/components/SideDrawer/Form/Fields/Action.tsx
- www/src/components/Table/formatters/Action.tsx
- www/src/components/Table/formatters/withCustomCell.tsx
- www/src/util/fns.ts
ensures we can still send emails even if calculation returns a NaN
> remove NaNs from row data in Action cell cloud function call

- cloud_functions/functions/src/callable.ts
- cloud_functions/functions/src/synonyms/config.ts
- www/src/components/Table/TableHeader.tsx
- www/src/components/Table/formatters/Action.tsx
- www/src/hooks/useFiretable/useTable.tsx
fixes issue with upstreet's db
> fix json field being set to empty string + other bug fixes

- src/hooks/useTable/useTableData.tsx
- src/utils/fns.ts
> fix csv import, items getting the same key

- src/hooks/useTable/useTableData.tsx
- src/utils/fns.ts
> Revert "fix csv import, items getting the same key"

- src/hooks/useTable/useTableConfig.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description
> fix delete bug: add fcn expression to sort in ascending order

- src/components/TableHeader/Export/Export.tsx
- src/components/TableHeader/Filters/index.tsx
- src/components/TableHeader/ImportCsv.tsx
- src/components/TableSettings/ActionsMenu/ExportSettings.tsx
- src/components/TableSettings/ActionsMenu/ImportSettings.tsx
- src/components/Wizards/ImportCsvWizard/index.tsx
analytics added for
1.  Filter Component's local and table filter
2. TableSetting Component's import and export settings
3. ImportcCSV 's Upload, Paste, and Url
4. CSVWizard's on success import
IN addition when user upload load wrong document, it breaks the app
Error handling w/ snackbar was added to onDrop. 
Finally. Helper function w/ Regex, use to detect if user is adding csv and tsv.
It handles edge case where a table is between quotes.
> Add a few logEvents for Analytics

- src/components/SideDrawer/FieldWrapper.tsx
- src/constants/externalLinks.ts
- src/utils/ui.ts
Copy button for Document Path:
- Added copy button.
- Displaying a Snackbar indicating copied
https://github.com/rowyio/rowy/issues/824
> Copy Document Path to Clipboard

- src/components/TableModals/ExtensionsModal/ExtensionList.tsx
- src/components/TableModals/ExtensionsModal/ExtensionsModal.tsx
- src/components/TableModals/ExtensionsModal/RuntimeOptions.tsx
- src/components/TableModals/ExtensionsModal/utils.ts
- src/constants/externalLinks.ts
- src/types/table.d.ts
Adds function's runtime configuration as part of https://github.com/rowyio/backend/pull/20#issue-1417689430:
Accordion expanded:
Incompatible version:
> Feat: Runtime options

- src/components/fields/Derivative/ContextMenuActions.tsx
Derivative evaluation might fail due to Rowy Run out of memory.
Instead of "failed to fetch", 
display the issue and ask user to increase memory in GCP console.
> Better derivative evaluation out of memory error message

- src/atoms/tableScope/ui.ts
- src/components/TableToolbar/ImportData/ImportData.tsx
- src/components/TableToolbar/ImportData/ImportFromCsv.tsx
Accept JSON -> convert JSON to CSV -> parse CSV
> ROWY-844 Feat: Import JSON

- src/hooks/useFirestoreDocWithAtom.ts
- src/sources/TableSourceFirestore/TableSourceFirestore.tsx
used `useUpdateAtom` to fix [this](https://github.com/rowyio/rowy/pull/1048).
> fix: optimistic update

- src/components/CodeEditor/CodeEditorHelper.tsx
- src/components/ColumnModals/ColumnConfigModal/DefaultValueInput.tsx
- src/components/TableModals/ExtensionsModal/utils.ts
- src/components/TableModals/WebhooksModal/AddWebhookButton.tsx
- src/components/TableModals/WebhooksModal/Schemas/basic.tsx
- src/components/TableModals/WebhooksModal/Schemas/sendgrid.tsx
- src/components/TableModals/WebhooksModal/Schemas/stripe.tsx
- src/components/TableModals/WebhooksModal/Schemas/typeform.tsx
- src/components/TableModals/WebhooksModal/Schemas/webform.tsx
- src/components/TableModals/WebhooksModal/WebhookModal.tsx
- src/components/TableModals/WebhooksModal/utils.tsx
- src/components/fields/Action/templates.ts
- src/components/fields/Connector/utils.ts
- src/components/fields/Derivative/Settings.tsx
- src/components/fields/Formula/Settings.tsx
- src/components/fields/Formula/util.tsx
- Add comments to not write code outside of the function body
- Update code style and make indentation consistent
- Add doc link to Formula code editor
> ROWY-879: code templates update

- src/atoms/projectScope/rowyRun.ts
- src/components/ColumnModals/ColumnConfigModal/DefaultValueInput.tsx
- src/components/ColumnModals/FieldsDropdown.tsx
- src/components/fields/Action/index.tsx
- src/components/fields/Connector/index.tsx
- src/components/fields/Derivative/index.tsx
- src/components/fields/types.ts
Currently if I continue to use Derivative without Rowy Run, evaluate will always show "cell evaluated" and function builder is always stuck at pending.
This PR requires cloud function setup before user is able to create the column by disabling the option and ask for setup.
https://user-images.githubusercontent.com/34177142/211042459-f04b529d-eeff-49ef-b732-2f6381721512.mov
> ROWY-818: requires cloud function setup before creating related columns

- src/atoms/projectScope/project.ts
- src/atoms/projectScope/ui.ts
- src/sources/ProjectSourceFirebase/useTableFunctions.ts
- src/types/table.d.ts
Added support to import/export sub tables 
Fix for issue [#621](https://github.com/rowyio/rowy/issues/601)
> ROWY-196: feat support copying subtables

- src/components/fields/SingleSelect/Settings.tsx
Add Reorder Select and Multi-select Field using react-dnd
> Reorder Select, MultiSelect field 515

- src/components/ColumnModals/ColumnConfigModal/DefaultValueInput.tsx
- src/components/TableModals/ExtensionsModal/utils.ts
- src/components/TableModals/WebhooksModal/Schemas/basic.tsx
- src/components/TableModals/WebhooksModal/Schemas/sendgrid.tsx
- src/components/TableModals/WebhooksModal/Schemas/stripe.tsx
- src/components/TableModals/WebhooksModal/Schemas/typeform.tsx
- src/components/TableModals/WebhooksModal/Schemas/webform.tsx
- src/components/fields/Action/templates.ts
- src/components/fields/Connector/utils.ts
- src/components/fields/Derivative/Settings.tsx
Adds a `logging.log` statements to code templates as an example usage
> ROWY-904: default logging statements

- src/layouts/AuthLayout.tsx
This PR centers the content on the AuthLayout of the sign out screen
> #ROWY-851: Centered sign out screen

- src/components/fields/Array/DisplayCell.tsx
- src/components/fields/Array/SideDrawerField/AddButton.tsx
- src/components/fields/Array/SideDrawerField/SupportedTypes.ts
- src/components/fields/Array/SideDrawerField/index.tsx
- src/components/fields/Array/SideDrawerField/utils.ts
- src/components/fields/Array/index.tsx
- src/components/fields/index.ts
- src/constants/fields.ts
> ROWY-688: New field Array

- src/components/ColumnMenu/ColumnMenu.tsx
- src/components/Table/ColumnHeader/ColumnHeader.tsx
- src/components/Table/ColumnHeader/ColumnHeaderSort.tsx
- src/components/Table/ColumnHeader/useSaveTableSorts.tsx
- src/components/TableToolbar/Filters/Filters.tsx
- src/pages/Table/TablePage.tsx
- src/sources/TableSourceFirestore/TableSourceFirestore.tsx
- src/sources/TableSourceFirestore/useApplySorts.ts
- src/types/table.d.ts
It will ask if this sorting should be applied to all users when we sort by a field.
If yes, then every time that table opens then the sorting will be applied by default.
> ROWY-444: Save sort on the table

- src/components/CodeEditor/CodeEditor.tsx
- src/components/CodeEditor/useMonacoCustomizations.ts
Adds a yellow underline warning to code if user types console and a quick action to replace with Rowy Logging.
> Add code action: replace console.log with logging.log

- src/components/Table/Table.tsx
- src/components/Table/useStateWithRef.ts
- src/components/Table/useTraceUpdates.ts
> ROWY-805: Fix resizing app crash

- src/atoms/projectScope/project.ts
- src/components/CodeEditor/useMonacoCustomizations.ts
- src/components/TableModals/WebhooksModal/Schemas/basic.tsx
- src/components/TableModals/WebhooksModal/Schemas/firebaseAuth.tsx
- src/components/TableModals/WebhooksModal/Schemas/sendgrid.tsx
- src/components/TableModals/WebhooksModal/Schemas/stripe.tsx
- src/components/TableModals/WebhooksModal/Schemas/typeform.tsx
- src/components/TableModals/WebhooksModal/Schemas/webform.tsx
- src/components/TableModals/WebhooksModal/Step1Auth.tsx
- src/components/TableModals/WebhooksModal/utils.tsx
- src/sources/ProjectSourceFirebase/useTableFunctions.ts
This PR implements secret names atom and reduces the endpoint calls to once only.
> ROWY-896: Feature/optimise listsecrets

- src/atoms/tableScope/rowActions.ts
- src/components/SideDrawer/MemoizedField.tsx
- src/components/SideDrawer/SideDrawerFields.tsx
- src/components/fields/Array/SideDrawerField/index.tsx
- src/components/fields/Formula/DisplayCell.tsx
- src/components/fields/Formula/SideDrawerField.tsx
- src/components/fields/Formula/index.tsx
- src/components/fields/Formula/useFormula.tsx
- src/components/fields/types.ts
- src/utils/table.ts
This change resolves the issue #1218 by introducing a new SideDrawerField component specifically for the Formula field and making appropriate changes to the codebase to utilize this new component.
/claim #1218
> Implement and Add SideDrawerField for Formula Field

- src/components/Table/ContextMenu/MenuContents.tsx
- src/hooks/useFirestoreDocAsCollectionWithAtom.ts
> Array Subtable bug fixes

- src/components/ColumnMenu/ColumnMenu.tsx
This PR fixes issue #1282. Now, it adds a new column on the left side of the selected column.
> Fix: change the value of the column index

- src/components/TableToolbar/Filters/Filters.tsx
- src/components/TableToolbar/Filters/utils.tsx
- src/types/table.d.ts
#1071 
- Added new feature: filter parameters in page URL.
- Ability to edit filter parameters using URL elements.
- Included loom link for reference. (https://www.loom.com/share/ddf8a5b2817a4700a518054e1b5d7d4e)
- Pull request submission for Issue #1071.
> Filter url

- src/components/RichTextEditor.tsx
- src/components/fields/RichText/SideDrawerField.tsx
Solves #1323
/claim #1323 
[Screencast from 2023-06-28 03-07-41.webm](https://github.com/rowyio/rowy/assets/107614965/f0d5f894-3cad-4059-bd4c-9d4e7ab76d64)
>  Ability to add images to richtext field

- src/components/Table/TableBody.tsx
- src/components/Table/TableHeader.tsx
/claim #1463
Freezed the selection column by simply adding data-frozen attribute.
Video: https://github.com/rowyio/rowy/assets/58873530/547548af-24e3-4914-bfa7-ff701a333eb1
> fix/Bug with the bulk selection column with freeze columns 

- src/components/TableToolbar/Filters/Filters.tsx
- src/components/TableToolbar/Filters/useFilterUrl.tsx
/claim #1478
Solves #1478 
https://github.com/rowyio/rowy/assets/68044488/b030a20f-c0f1-49c1-9fcb-6b1ad9b13045
> fix: subtable filters refresh bug

- src/components/TableToolbar/Filters/FilterInputs.tsx
- src/components/fields/Number/SideDrawerField.tsx
> fix: #1483 Applying filters using table

- src/hooks/useFirestoreCollectionWithAtom.ts
> fix "is-not-empty" filter

- package.json
- src/components/ColumnModals/FieldsDropdown.tsx
- src/components/fields/Array/index.tsx
- src/components/fields/Checkbox/index.tsx
- src/components/fields/Code/index.tsx
- src/components/fields/Color/index.tsx
- src/components/fields/CreatedAt/index.tsx
- src/components/fields/CreatedBy/index.tsx
- src/components/fields/Formula/index.tsx
- src/components/fields/GeoPoint/index.tsx
- src/components/fields/Id/index.tsx
- src/components/fields/Image/index.tsx
- src/components/fields/LongText/index.tsx
- src/components/fields/Markdown/index.tsx
- src/components/fields/MultiSelect/index.tsx
- src/components/fields/Number/index.tsx
- src/components/fields/Phone/index.tsx
- src/components/fields/Rating/index.tsx
- src/components/fields/RichText/index.tsx
- src/components/fields/ShortText/index.tsx
- src/components/fields/SingleSelect/index.tsx
- src/components/fields/UpdatedAt/index.tsx
- src/components/fields/UpdatedBy/index.tsx
- src/components/fields/Url/index.tsx
- src/components/fields/User/index.tsx
- src/components/fields/types.ts
- yarn.lock
/claim #1529
/fixes #1529
https://github.com/rowyio/rowy/assets/64700961/0266c4d3-2b4d-436a-aa4a-382472070607
> [1529] Fuzzy Search on Column Types
