www/src/Theme.tsx
www/src/components/SideDrawer/Form/Autosave.tsx
www/src/components/SideDrawer/Form/index.tsx
www/src/components/SideDrawer/index.tsx
www/src/components/SideDrawer/useStyles.ts
www/src/components/Table/editors/SideDrawerEditor.tsx
www/src/components/Table/formatters/withCustomCell.tsx
www/src/components/Table/index.tsx
www/src/contexts/firetableContext.tsx

Fixes slow cell selection due to side drawer state being stored in firetableContext.
firetableContext now stores a ref to side drawer’s state to be able to update the selected cell and open/close the drawer from anywhere in the app
Also improves animations in side drawer

Performance: side drawer cell selection

---

www/src/components/TableSettings/form.tsx

Hello, I am setting up Firetable for the first time and I was cracking my head around why my tables are not visible in the side menu. I think that the helper text is misleading as I was passing user email instead of role to this field. 
I propose to change `users` to `roles` which is more appropriate.

update helper text in create table form

---

www/src/components/Table/TableHeader/ForceRefresh.tsx
www/src/components/Table/TableHeader/index.tsx

Add a force refresh button to update the _ft_forcedUpdateAt time for all documents in a collection resulting in the sparks (and derivatives when combined with my previous push) refreshing for all documents.
Force refresh button will be hidden if the user is not admin or the table contains no sparks or derivatives
Example:
**Step 1: Adding a new derivative:**
https://www.loom.com/share/8f5289495a074217a9d384bceff569e1
**Step 2: Force Refresh:**
https://www.loom.com/share/e1f831bdb3ba43dbb5fc398e2a1e3336

add force refresh derivatives/sparks to table header

---

README.md
www/src/components/TableSettings/form.tsx

When creating a table user can choose to copy column config. 
The previous version doesn't allow users to clear this selection once they select. 
This PR adds a clear button to fix that

allow user to clear column config selection in create table

---

src/hooks/useTable/useTableConfig.ts

- Use javascript delimiter to create a deep copy of the object
- reactor to allow higher order function to reuse array and readability

fix bug: prevent unintended state mutation

---

src/hooks/useTable/useTableConfig.ts
src/utils/fns.ts

#559 
- Use .reduce() to carry out data swap, and 
- transform columns into a correct data structure for dispatch. 
Details about Data swap
- During interaction, 
if curr.key === a.key, then copy data[b],  index 
vice versa === b.key, acc[a.key] =  { ...data[a], index }
I do request some clarification on the array mover function.
- When is there an undefined element?
I don't fully understand the arrayMover function. 
I think I am missing an edge case, assistance would be awesome.

fix-bug #559 unpredictable state of tableAction.reorder's function

---

src/assets/icons/Cut.tsx
src/assets/icons/Paste.tsx
src/components/Table/ColumnMenu/index.tsx
src/components/Table/ContextMenu/MenuContent.tsx
src/components/Table/ContextMenu/MenuRow.tsx
src/components/Table/ContextMenu/index.tsx
src/components/Table/TableRow.tsx
src/components/Table/index.tsx
src/components/fields/Email/index.tsx
src/components/fields/LongText/index.tsx
src/components/fields/Number/index.tsx
src/components/fields/Phone/index.tsx
src/components/fields/RichText/index.tsx
src/components/fields/ShortText/index.tsx
src/components/fields/Status/ConditionModalContent.tsx
src/components/fields/Url/index.tsx
src/components/fields/_BasicCell/BasicCellContextMenuActions.tsx
src/components/fields/types.ts
src/contexts/ProjectContext.tsx
src/hooks/useTable/useTableConfig.ts

#600 
Enable Right click on designated Field Types

Right click menu

---

src/components/SideDrawer/Form/index.tsx

We were unable to update values of select fields pointing to nested keys and lost a lot of data as the UI was showing that it's saved, but in fact it wasn't.

Fix initial values for nested fields

---

src/components/Table/ContextMenu/MenuContents.tsx
src/components/Table/formatters/FinalColumn.tsx

Fixes #739
This PR adds a confirmation modal for adding a duplicate row.

Added confirmation for Duplicate Row button

---

README.md
src/components/fields/Action/ActionFab.tsx

Refactored logic in Action Fab to ensure that un-checking the "Custom button icons with emoji" button in the config settings for an Action field will revert icons to default.

#816: Fixed Logic for Custom Icons in Action Field

---

README.md
src/components/fields/Rating/Settings.tsx
src/components/fields/Rating/SideDrawerField.tsx
src/components/fields/Rating/TableCell.tsx

#513: Added Customizable Icons for Rating Field
Demonstration here (no audio): https://www.loom.com/share/b4738b9a8a4e45e0bd9c945d9a203388 (Video demo updated to reflect side drawer and icon size updates)
Note: While working on this ticket, I encountered a bug that I created an issue for here #816. I also received some great design feedback that I wish I had time to work on, but don't think I will at the moment (at least during this one day open source challenge!).

#513: Added Customizable Icons for Ratings Field

---

.github/ISSUE_TEMPLATE/config.yml
README.md
src/components/fields/LongText/Filter.tsx
src/components/fields/LongText/Settings.tsx
src/components/fields/LongText/index.tsx
src/components/fields/ShortText/index.tsx

Signed-off-by: Raj Gaurav Maurya <rajgmsocial19@gmail.com>

Feat: Customization options added to long text field

---

src/components/fields/Action/Settings.tsx

This PR modifies the settings for the Action field to default to a user-declared script instead of a cloud function that they've already deployed to Firestore/GCP.

Changed default Action to script from cloud func

---

src/components/TableModals/CloudLogsModal/BuildLogs/BuildLogsSnack.tsx

PR fixes build logs collapse by default when building derivative column function. 
Fixes #693 
**Changelog**: 
- Fixes `Box` in `BuildLogsSnack.tsx` height if not expanded.
- Hide/Show logs based on `expanded` boolean.
[Demo](https://www.dropbox.com/s/3y55ycho345izxa/rowy_pr.mp4?dl=0)

fix: Build logs collapse by default

---

src/components/CodeEditor/DiffEditor.tsx

This PR applies the same fix that was applied to the code editor, to diff editor.
Before fix:
After fix:

 Fix diff editor dark theme ui

---

src/components/TableToolbar/HiddenFields.tsx

[#562](https://github.com/rowyio/rowy/issues/562): Add accessible reorder option in column menu.
Worked on this improvement.
I started by creating a new file ManageColumns.tsx and keeping HiddenFields.tsx as the base.
I have used [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) as recommended.
_Linked to PR [#983 ](https://github.com/rowyio/rowy/pull/983) -> created because of some issue with branch._

#562: Add accessible reorder option in column menu [new]

---

src/atoms/projectScope/project.ts
src/components/TableModals/ImportAirtableWizard/ImportAirtableWizard.tsx
src/components/TableModals/ImportCsvWizard/ImportCsvWizard.tsx
src/components/TableTutorial/Steps/Step2Add.tsx
src/components/fields/Connector/Select/PopupContents.tsx
src/hooks/useFirestoreDocWithAtom.ts
src/sources/ProjectSourceFirebase/useTableFunctions.ts

As seen in https://github.com/rowyio/rowy/discussions/1037, some objects may be undefined before accessing .some function. This PR adds null checking for it in an attempt to resolve the issue.
Error stack for tracing id `ROWYERR-F917-CEEA-490C-78540106AD05`
_TypeError: Cannot read properties of undefined (reading 'some')\n    at https://rowy.app/static/js/main.3928d7f4.js:205:2244554\n    at Array.filter (<anonymous>)\n    at Object.read (https://rowy.app/static/js/main.3928d7f4.js:205:2244485)\n    at k (https://rowy.app/static/js/main.3928d7f4.js:205:2631450)\n    at Object.I [as r] (https://rowy.app/static/js/main.3928d7f4.js:205:2631763)\n    at s (https://rowy.app/static/js/main.3928d7f4.js:205:2635381)\n    at https://rowy.app/static/js/main.3928d7f4.js:205:2635585\n    at Object.Ca …

null checking on .some functions

---

package.json
src/components/Table/ContextMenu/BasicCellContextMenuActions.tsx
src/components/Table/Table.tsx
src/contexts/TableKbShortcutContext.tsx
yarn.lock

https://user-images.githubusercontent.com/62830866/210532049-a512931a-34e6-4694-8443-9bc5db55cf19.mp4
1. created `useMenuAction` hook to handle the task in order to make the functions common for both the scenarios (keyboard shortcut, context menu).
2. created `TableKbShortcutContext` context to wrap around the table to listen for the events and handle accordingly.
3. used [`useHotkeys`](https://mantine.dev/hooks/use-hotkeys/) to listen to keyboard shortcuts.

ROWY-850 Feat: copy paste keyboard shortcut

---

src/components/TableModals/ImportAirtableWizard/Step1Columns.tsx
src/components/TableModals/ImportCsvWizard/Step1Columns.tsx
src/components/TableModals/ImportExistingWizard/Step1Columns.tsx

This PR adds a "select all" option to the CSV and Airtable import wizards, allowing users to select all columns or fields of their Airtable or CSV tables to import at once.

#ROWY-763: Import wizard select all

---

src/components/CodeEditor/rowy.d.ts

Allows Rowy Logging to accept multiple parameters just like console.log
If 1 item is passed in to `logging.log`, it will be displayed the same way as before. If more than 1 items are passed in, an array will be displayed in Rowy Logging.
E.g. `logging.log("error", e.message)`
Backend PRs:
- https://github.com/rowyio/backend/pull/28/
- https://github.com/rowyio/rowy-hooks/pull/4

ROWY-912: allow multiple params for logging

---

src/atoms/projectScope/ui.ts
src/components/Table/ContextMenu/MenuContents.tsx
src/components/Table/FinalColumn/FinalColumn.tsx
src/components/TableToolbar/AddRow.tsx
src/types/table.d.ts

This PR enables using `idType` in `tableSchema`. Default value still stays as `decrement` type, so no backward compatibility issues expected.
The logic behind `addRowAtom` is still problematic in some cases, I'll create another Linear issue for that.

Persist id customization at table level

---

src/components/fields/Date/index.tsx
src/components/fields/DateTime/index.tsx

If date/datetime is a number, it will not have `toDate` thus causing export to crash. Easy fix by adding the handler for this case.

fix export crash due to toDate issue

---

src/components/ColumnModals/ColumnConfigModal/DefaultValueInput.tsx
src/components/fields/Action/templates.ts
src/components/fields/Connector/utils.ts
src/components/fields/Derivative/Settings.tsx

This PR updates the function default templates to the ESM syntax

Add ESM support

---

src/components/Table/ContextMenu/BasicCellContextMenuActions.tsx
src/components/Table/useMenuAction.tsx
src/components/fields/Array/index.tsx
src/components/fields/Checkbox/index.tsx
src/components/fields/Code/index.tsx
src/components/fields/Color/index.tsx
src/components/fields/CreatedAt/index.tsx
src/components/fields/CreatedBy/index.tsx
src/components/fields/Date/index.tsx
src/components/fields/DateTime/index.tsx
src/components/fields/Duration/index.tsx
src/components/fields/File/ContextMenuActions.tsx
src/components/fields/File/index.tsx
src/components/fields/GeoPoint/index.tsx
src/components/fields/Markdown/index.tsx
src/components/fields/MultiSelect/index.tsx
src/components/fields/Rating/index.tsx
src/components/fields/SingleSelect/index.tsx
src/components/fields/Slider/index.tsx
src/components/fields/UpdatedAt/index.tsx
src/components/fields/UpdatedBy/index.tsx

This change resolves the issue #1154.
Furthermore, the update includes a new functionality that limits the fields where values can be pasted using the hotkey. Prior to this update, the hotkey allowed for the pasting of values in any field type, including read-only fields like CreatedBy, CreatedAt. This created the possibility for data corruption, as read-only fields could be modified. The new feature prevents such accidental modifications by restricting the fields where the hotkey can be used, ensuring that read-only fields remain unmodifiable.

Expand support for fields that can be copied to clipboard

---

src/components/Table/TableCell/EditorCellTextField.tsx
src/components/fields/Number/EditorCell.tsx
src/components/fields/Number/SideDrawerField.tsx
src/components/fields/Percentage/EditorCell.tsx
src/components/fields/Percentage/SideDrawerField.tsx
src/components/fields/types.ts

Chrome has some slightly unique input[type="number"] handling behaviour, where it restricts the characters that can be typed to numeric characters. Under-the-hood, Chrome withholds certain invalid input states from being emitted as change events – so we only receive change events for valid numbers.
Safari behaves slightly differently. It allows any characters to be entered and emits a change event on each character press, but its internal "value" is only set if the typed input is a valid number. The change events then either come through with a numeric value represented, or as an empty string.
For example, when typing "12.34" we receive onChange events with "1", "12", "", "12.3", and "12.34".
On that third onChange event when we pass "" up to React, React happily ignores the change (I …

Fix Safari turning decimal number inputs to 0

---

src/components/ColumnMenu/ColumnMenu.tsx
src/components/Table/ColumnHeader/ColumnHeaderSort.tsx
src/components/TableToolbar/Sort/Sort.tsx
src/components/TableToolbar/Sort/SortPopover.tsx
src/components/TableToolbar/Sort/index.tsx
src/components/TableToolbar/TableToolbar.tsx

closes #1244 
This PR adds a sort button which is visible only when the sort is applied on a column. Clicking on sort button opens a popover where the user can select other columns for sorting and as well as select the sorting direction i.e. ascending or descending.
Also on a side note, I noticed that even if you remove the sort, it is not removed from the Firebase and if you reload the page after removing the sort, it will be reapplied on the table. This should be an easy fix and I can do it in this PR if you say so.
/claim #1244

Sort button to showcase if a column is sorted or not

---

src/components/Table/ContextMenu/MenuContents.tsx

"Filter by" option to filter by the value of the cell

---

package.json
src/components/Table/EmptyTable.tsx
src/components/TableToolbar/LoadedRowsStatus.tsx
yarn.lock

Rowy displays "offline" error and prevents users from entering table page as seen a couple of times. 
- https://github.com/rowyio/rowy/discussions/1278#discussion-5269786
- https://discord.com/channels/853498675484819476/1109429020896014439/1109429020896014439
The issue is caused by the package [react-detect-offline](https://github.com/cwise89/react-detect-offline/issues/112) that is not maintained since 2021 and affects Chrome on Windows, Firefox on Windows, and Chrome on Linux, because its polling solution no longer works.
This PR uses [navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) as a replacement. As of today, this property has [full support](https://caniuse.com/?search=navigator.onLine) from Chrome, Firefox and Safari. According to the spec, if …

Fix false offline error

---

src/components/fields/SingleSelect/Settings.tsx

Edit functionality for options of single select and multi select fields

---

src/components/TableToolbar/AddRow.tsx

As seen in https://github.com/rowyio/rowy/discussions/1072, the disabled "add row" button is confusing in collection group. Adding a tooltip for clarification. Tooltip only displays for collection group, no change for normal collection.

add clarification tooltip to "add row" button for collection group

---

src/components/TableSettingsDialog/TableName.tsx

Fixes the following issues on the create table form:
- First table creation, table name field only automatically gets the first character of collection name, not full collection name.
- Non-first table creation, table name field does not get updated when collection name updates after the first selection.
- Full deletion of table name field populates the field with value from collection name, it should become empty.
Current implementation checks if table name field has values. After getting value from collection name (first collection name character for first table, or first collection name choice for non-first table), the code logic would omit any changes from collection name, causing the issues mentioned above.
New implementation checks if table name field is touched. If not touched, it …

fix create table form table name glitches

---

src/components/Table/useMenuAction.tsx
src/components/fields/Reference/index.tsx

This PR adds copy/paste functionality for reference field through hotkeys and context menu actions.
[Screencast from 2023-06-26 14-35-19.webm](https://github.com/rowyio/rowy/assets/107614965/10800532-3e5c-4d20-8d7d-afd01f6e5a7f)
Closes #1319 
/claim #1319

Add copy/paste functionality for reference field

---

src/components/Table/EmptyTable.tsx

This PR fixes issue #1284. Now, Rowy can detect and suggest the schema for the array suitable.
https://github.com/rowyio/rowy/assets/57035408/327b92aa-dda0-4e1b-b950-f11b7b3de59c

Implement auto import for array subtables

---

src/components/TableSettingsDialog/form.tsx

As seen in Discord support, table function deploy will fail if collection name contains dots. This PR adds validation on table creation modal to prevent such collection names being used.
(https://discord.com/channels/853498675484819476/1118858045460598797/1118860716556963910)

disallow dots in collection name

---

src/components/TableModals/CloudLogsModal/BuildLogs/BuildLogsSnack.tsx

This PR fixes a bug. There is no issue for this bug so feel free to reject this PR. I found this behavior while browsing around the app and it seemed like a quick fix. Hence this PR. 
When the `BuildLogsSnack` is maximized, clicking full screen should minimize the component before opening the modal.
https://github.com/rowyio/rowy/assets/4337699/5309d8eb-17e9-4220-ba7c-6dcfd6181a65
https://github.com/rowyio/rowy/assets/4337699/49f12978-11df-41d1-8efe-3b450645e4f0

fix bug: minimize `BuildLogsSnack` upon fullscreen

---

src/components/CodeEditor/useMonacoCustomizations.ts

This PR adds support for code editor quick replacements for `rowy.secrets.get` method if the provided secret name does not exist.
The list of replacement values are sorted by similarity of the provided secret name. For example, if user types a typo "whatapp" and the correct secret "whatsapp" exists in GCP Secret Manager, it will appear on the top of the list.

Add code editor quick action to get secrets

---

src/components/fields/Array/Filter.tsx
src/components/fields/Array/SideDrawerField/index.tsx
src/components/fields/Array/index.tsx
src/components/fields/types.ts
src/hooks/useFirestoreCollectionWithAtom.ts

fix: FEAT: Array column should be filterable

---

src/components/Table/Table.tsx
src/components/Table/TableBody.tsx
src/components/Table/TableHeader.tsx
src/components/Table/useVirtualization.tsx
src/components/TableToolbar/TableToolbar.tsx
src/pages/Table/ProvidedArraySubTablePage.tsx
src/pages/Table/ProvidedSubTablePage.tsx
src/pages/Table/ProvidedTablePage.tsx
src/pages/Table/TablePage.tsx
src/theme/CheckboxIndeterminateIcon.tsx

This PR adds support for bulk deletion of rows by implementing a checkbox next to each row. The implementation is based on the [example](https://tanstack.com/table/v8/docs/examples/react/row-selection) provided by react-table.
- Selecting a few rows should put the header checkbox in an [indeterminate](https://mui.com/material-ui/react-checkbox/#indeterminate) state. For some reason it is not working. I don't see any problem with my code/logic.
- Sometimes, after deleting rows the [`<LoadedRowStatus />`](https://github.com/rowyio/rowy/blob/develop/src/components/TableToolbar/LoadedRowsStatus.tsx) component doesn't update the total number of rows. I request someone with more experience of the codebase to look into it.
- The state for managing selected rows is set by react-table. They [set …

add support for bulk deletion of rows

---

src/atoms/tableScope/table.ts
src/atoms/tableScope/ui.ts
src/components/ColumnMenu/ColumnMenu.tsx
src/components/ColumnModals/ColumnModals.tsx
src/components/ColumnModals/SetColumnWidthModal.tsx
src/components/Table/Table.tsx

Fixes #563.
- Created a new atom to store the table.
- Width is updated via `setColumnSizing()`.
- The _"Save column sizes for all users?"_ prompt shows up upon updating the width.
Functioning:
- Adds an option to the column context menu -- "Set Column Width". Option is disabled if resizing is disabled.
- Selecting it opens up a modal with a single number input field, pre-filled with the current width of the column.
- Entering a new value and hitting Update resizes the column as needed.

Add an accessible resizing option

---

src/atoms/projectScope/user.ts
src/components/Settings/UserSettings/TableSettings.tsx
src/components/Table/ColumnHeader/useSaveTableSorts.tsx
src/components/Table/useSaveColumnSizing.tsx
src/pages/Settings/UserSettingsPage.tsx
src/types/settings.d.ts

Fixes #1386. Adds a new `Table Settings` section to the user's settings page. The section contains check-boxes which the user may use to alter the save-popups' behavior.

Allow for disabling save popups in tables

---

src/components/TableModals/ImportCsvWizard/ImportCsvWizard.tsx
src/components/TableModals/ImportCsvWizard/Step1Columns.tsx

A "proof-of-concept"-ey implementation of what [the 2nd solution](https://github.com/rowyio/rowy/issues/1418#issuecomment-1736043543) could look like for #1418.
Field key values are just the column name in camelCase by default, can now be edited.

Ability to edit field keys when importing CSVs

---

src/components/Table/Table.tsx
src/components/Table/useHotKey.tsx
src/components/Table/useMenuAction.tsx

Allows for pasting content into table cells using hotkeys in Firefox.

Retrieve clipboard data from ClipboardEvent instead

---

src/App.tsx
src/atoms/projectScope/ui.ts
src/components/ProjectSettingsDialog/ProjectSettingsDialog.tsx
src/components/ProjectSettingsDialog/SecretDetailsModal.tsx
src/components/ProjectSettingsDialog/index.ts
src/components/TableModals/WebhooksModal/Schemas/stripe.tsx
src/components/TableSettingsDialog/TableSettingsDialog.tsx
src/constants/runRoutes.ts

This PR implements secret management popup and is currently used by Stripe webhook auth section. It will be easy to open the popup in other places where secret management is needed as well.

Add secret management popup

---

src/components/TableSettingsDialog/TableName.tsx
src/components/TableSettingsDialog/form.tsx

closes #1409 
It was watching the wrong field i.e. collection due to which the watchvalue will always be equal to the collection name. 
Also, I have added consistency in the startCase through which if you switch your input focus and comeback again on tablename field the startCase consistency would be maintained.

Table name textbox UI error fix

---

src/components/TableInformationDrawer/Details.tsx
src/components/TableInformationDrawer/TableInformationDrawer.tsx
src/components/TableSettingsDialog/ActionsMenu/ActionsMenu.tsx
src/components/TableSettingsDialog/DeleteMenu.tsx
src/pages/TablesPage.tsx

Fixes #1411 
Added tooltips to various buttons.
Screenshot -
P.S. - I noticed most of the buttons on the Rowy web app are without tooltips. I can update them in this PR.
We can classify where we need tooltips depending on the button.
1. If the button is too obvious, I don't think a tooltip is necessary.
2. If the button is to clarify an immediate operation, a tooltip can be useful.
What do you say? @harinij

feat: added tooltip to buttons

---

src/components/TableModals/ExtensionsModal/utils.ts

Fixes https://discord.com/channels/853498675484819476/1167845816543744190/1167845816543744190.
There is a typo in the BuildShip extension template. `change.before.get` is used to get a single field which expects an argument, in this template, `change.before.data` is the correct method as it returns the document data.

fix buildship template change object

---

src/components/TableToolbar/TableToolbar.tsx

Fixes #1455 
This PR adds a confirmation modal for deleting rows in bulk.

Added confirmation for bulk deletion of rows

---

src/sources/ProjectSourceFirebase/init.ts

Firestore docs states that [the enableMultiTabIndexedDbPersistence API is now obsolete](https://firebase.google.com/docs/reference/js/firestore_#enablemultitabindexeddbpersistence).
This PR updates the usage to the [latest doc](https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_offline_persistence).

update deprecated firestore cache settings

---

src/components/TableModals/ImportCsvWizard/ImportCsvWizard.tsx

**User's issue:**
User have reported an issue with batch importing CSV files when selecting a custom column for Document IDs. Although importing the same CSV with auto-generated Document IDs works, choosing a specific column as Document IDs leads to an error: "n.charAt is not a function."
**Cause:**
Column types like reference and image, require custom parsers. Previously, these parsers were stored in an object with the column index as the key. However, when using a custom document ID, the explicit setting of the document ID resulted in a change to the column index reference.
**Fix:**
The fix involves using the column key as the key to store the parsers, rather than relying on the column index.

fix(CSV import): error while using a column as row id

---

src/components/TableSettingsDialog/TableName.tsx
src/components/TableSettingsDialog/form.tsx

https://github.com/rowyio/rowy/pull/1412 fixed https://github.com/rowyio/rowy/issues/1409 but broke the autofill of table name field which is derived from collection name.
This PR brings the autofill back and also fixed https://github.com/rowyio/rowy/issues/1409.

ROWY-2110 fix broken table id prefill for table setup

---

src/atoms/tableScope/rowActions.ts
src/components/fields/Formula/TableSourcePreview.ts

Sort does not work if table has formula column.
Example:  in this table setup, the right-most column is a formula column. The table sort is set to num descending, however the table UI displays rows order incorrectly.
In a [commit](https://github.com/rowyio/rowy/commit/2715a8094aa740bd6c783ad7e28fb24f6973cded#diff-2a9e818ac35e243edc7e9fa19ab3c1d03991ab452c82e1ececbef1b0ba93247eR389-R390) related to formula field, it sets all rows to `rowsLocal` if there is formula column in the table. 
https://github.com/rowyio/rowy/blob/2715a8094aa740bd6c783ad7e28fb24f6973cded/src/atoms/tableScope/rowActions.ts#L389-L391
`rowsLocal` is designed to hold our of order rows that are supposed to be a very small set, and they are always displayed at the top of the table UI. They are not sorted or ordered. …

Fix table sort does not work if table has formula column

---

src/hooks/useFirestoreCollectionWithAtom.ts

Applying any date or datetime filters will cause the whole table page to crash, and the crash persists until user manually visit debug page and reset filters.
Example: https://github.com/rowyio/rowy/discussions/1513
We expect `toDate` to be present in the filter value because it is supposed to be a Firestore `Timestamp` object.
```js
const filterDate =
"toDate" in filter.value ? filter.value.toDate() : filter.value;
```
This used to hold true, however, the recent [shareable filter url feature](https://github.com/rowyio/rowy/pull/1256) slightly changed the way filters are passed - it uses `JSON.stringify` on filters and set it in the url. When the values are parsed, we no longer get `Timestamp`. Instead, we get `{ nanoseconds: number; seconds: number }`, the Timestamp object without …

Fix datetime filters crash table page
